### ISSUE TITLE
Visual bug on Search input

### ISSUE THREAD

**Issue by adngdb** [peterbe/django-peterbecom#576]
Hey Peter,

On your website, when you hover on the Search input, it duplicates: 

Before:
![screenshot_2019-03-04 newsletters i enjoy for work](https://user-images.githubusercontent.com/328790/53728533-4584c100-3e73-11e9-9cc6-6a080d23a1ca.png)

After hover:
![screenshot_2019-03-04 newsletters i enjoy for work 1](https://user-images.githubusercontent.com/328790/53728541-49184800-3e73-11e9-8312-9db67a921e8f.png)

**Comment by peterbe** [comment]
Oh no! Not again. This *used* to be a bug and it's because how SemanticUI forces that elements are direct descendants. Which page did it happen on do you remember? Does it go away with a full refresh?

Thanks for sharing!

**Comment by adngdb** [comment]
It seems to be happening on any page of your site. A reload does make the state come back to normal, but then hovering the Search does the same. Nothing shows up in the console.

I'm on recent Nightly on Ubuntu.

**Comment by peterbe** [comment]
Wow! This makes so little sense. I did see it myself once or twice. That's when I realized my mistake (in how I used SemanticUI) and reverted it. 
But caching it long and slow so I too saw it even after I *knew* it was fixed in `master`. 

Today, I tried Nightly, Google Chrome, and Safari and clicked around a bunch. No need to Shift-Reload anything. None of the randomish pages I clicked on had the problem. 

So, could this be an Ubuntu-only problem??

If you can find a page on which it happens, without Reloading!, the right-click on the input (search) widget and "Inspect Element". WHat do you see? I see...
<img width="2038" alt="screen shot 2019-03-05 at 8 14 00 am" src="https://user-images.githubusercontent.com/26739/53807892-cf3d9880-3f1e-11e9-9fbd-e2194add6f87.png">

**Comment by adngdb** [comment]
I can reproduce on Firefox release, not on Chromium.

Here's my Inspector content on Nightly:
![](https://framapic.org/7R8hJyDp7JEA/UoKl8qiTyhwS.png)

**Comment by peterbe** [comment]
So it might not be a matter of CSS but a matter of JS. For some reason, on your browser the `._ac_result` doesn't have `display:none` whereas mine does. See:
<img width="998" alt="screen shot 2019-03-05 at 10 14 52 am" src="https://user-images.githubusercontent.com/26739/53815366-8a6e2d80-3f2f-11e9-9209-9ddd3f1315e5.png">

I think the root of this is somewhere in: https://github.com/peterbe/autocompeter/blob/master/src/autocompeter.js where it does things like `element.style.display = 'none'` and that's simply not always working. Which is weird.

**Comment by peterbe** [comment]
so many years ago.
